// src/src/App.vue
<script setup lang="ts">
import StreamItem from './components/StreamItem.vue';
import VolumeStep from './components/VolumeStep.vue';
import { useRadioPlayer } from './stores/RadioPlayer';

const radio = useRadioPlayer();
const refresh = () => window.location.reload();
</script>
<template>
  <div className="container-fluid mt-2">
    <div className="list-group list-group-flush">
      <StreamItem v-for="stream in radio.radioStreams" :key="stream.id" :stream="stream" />
      <button type="button" @click="radio.toggleRadio" class="text-center list-group-item list-group-item-action"
        :class="[radio.isPlaying ? 'list-group-item-danger' : 'list-group-item-primary']">
        <svg v-if="radio.isPlaying" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
          class="bi bi-stop-circle-fill" viewBox="0 0 16 16">
          <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.5 5A1.5 1.5 0 0 0 5 6.5v3A1.5 1.5 0 0 0 6.5 11h3A1.5 1.5 0 0 0 11 9.5v-3A1.5 1.5 0 0 0 9.5 5h-3z" />
        </svg>
        <svg v-else xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
          class="bi bi-play-circle-fill" viewBox="0 0 16 16">
          <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814l-3.5-2.5z" />
        </svg>
      </button>
    </div>
    <div className="d-flex justify-content-between">
      <div className="mt-4">
        <button className="btn btn-outline-primary" @click="refresh">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-clockwise"
            viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z" />
            <path
              d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z" />
          </svg><i className="bi bi-arrow-clockwise"></i>
        </button>
      </div>
      <div className="text-center mt-4">
        <div className="btn-group">
          <VolumeStep v-for="step in radio.volumeSteps" :key="step" :val="step" />
        </div>
      </div>
      <div className="mt-4">
        <button className="btn btn-outline-success" @click="radio.changeDevice">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-speaker"
            viewBox="0 0 16 16">
            <path
              d="M12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z" />
            <path
              d="M8 4.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5zM8 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 3a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-3.5 1.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>

// src/App.tsx
import React from "react";
import Config from "./Config";
import Radio from "./Radio";
import { useRadio } from "./RadioContext";
import Volume from "./Volume";
// import './App.css';

function App() {
  const radio = useRadio();
  const classes = `list-group-item list-group-item-action list-group-item-${
    radio.isPlaying ? "danger" : "primary"
    } text-center`;
  const refresh = () => {
    window.location.reload();
  };

  return (
    <div className="container-fluid mt-2">
      <div className="list-group list-group-flush">
        {Config.Streams.map((r) => (
          <Radio key={r.id} {...r} />
        ))}
        {radio.currentStation && (
          <button type="button" onClick={radio.toggle} className={classes}>
            {radio.isPlaying ? <i className="bi bi-stop-circle-fill"></i> : <i className='bi bi-play-circle-fill'></i>}
          </button>
        )}
      </div>
      <div className="d-flex justify-content-between">
        <div className="mt-4">
          <button className="btn btn-outline-primary" onClick={refresh}>
            <i className="bi bi-arrow-clockwise"></i>
          </button>
        </div>
        <div className="text-center mt-4">
          <div className="btn-group">
            {Config.VolumeSteps.map((v) => (
              <Volume key={v} vol={v} />
              ))}
          </div>
        </div>
        <div className="mt-4">
          <button className="btn btn-outline-success" onClick={radio.changeDevice}>
            <i className="bi bi-speaker"></i>
          </button>
        </div>
      </div>
    </div>
  );
}

export default App;
